import type { ModuleMeta } from "@/types/module";

// Source of truth for module metadata not stored in MDX frontmatter.
// Slugs MUST match content/modules/ directory names and content/manifest.json.
// Lesson slugs MUST match content/modules/[module]/lessons/lesson-N.es.mdx filenames.
export const MOCK_MODULES: ModuleMeta[] = [
  {
    slug: "passwords",
    title: "Contraseñas seguras",
    description: "Aprende a crear y gestionar contraseñas que nadie pueda adivinar.",
    icon: "🔑",
    difficulty: "basic",
    estimatedMinutes: 60,
    prerequisites: [],
    lessons: [
      { slug: "lesson-1", title: "Qué hace una contraseña segura", order: 1 },
      { slug: "lesson-2", title: "Cómo crear una frase de contraseña", order: 2 },
      { slug: "lesson-3", title: "Gestores de contraseñas", order: 3 },
      { slug: "lesson-4", title: "Cómo crear una contraseña maestra fuerte", order: 4 },
      { slug: "lesson-5", title: "Contraseñas en el trabajo", order: 5 },
      { slug: "lesson-6", title: "Qué hacer si te hackearon la cuenta", order: 6 },
    ],
  },
  {
    slug: "phishing",
    title: "Detecta el engaño antes de hacer clic",
    description: "Aprende a reconocer correos y mensajes falsos que intentan robarte información.",
    icon: "🎣",
    difficulty: "basic",
    estimatedMinutes: 45,
    prerequisites: [],
    lessons: [
      { slug: "lesson-1", title: "Cómo reconocer un correo de phishing", order: 1 },
      { slug: "lesson-2", title: "URLs sospechosas y dominios falsos", order: 2 },
      { slug: "lesson-3", title: "Phishing por WhatsApp y SMS (smishing)", order: 3 },
      { slug: "lesson-4", title: "Llamadas falsas de soporte técnico (vishing)", order: 4 },
      { slug: "lesson-5", title: "Phishing en redes sociales", order: 5 },
      { slug: "lesson-6", title: "Cómo reportar un intento de phishing", order: 6 },
      { slug: "lesson-7", title: "Simulacro mental", order: 7 },
    ],
  },
  {
    slug: "mfa",
    title: "Dos llaves son mejor que una",
    description: "Descubre cómo una segunda verificación protege tus cuentas incluso si alguien roba tu contraseña.",
    icon: "🔐",
    difficulty: "basic",
    estimatedMinutes: 30,
    prerequisites: ["passwords"],
    lessons: [
      { slug: "lesson-1", title: "Qué es la autenticación de dos factores", order: 1 },
      { slug: "lesson-2", title: "Apps autenticadoras vs SMS", order: 2 },
      { slug: "lesson-3", title: "Llaves de seguridad físicas", order: 3 },
      { slug: "lesson-4", title: "Qué hacer si pierdes tu segundo factor", order: 4 },
      { slug: "lesson-5", title: "MFA en el trabajo", order: 5 },
    ],
  },
  {
    slug: "simulators",
    title: "Simuladores de phishing",
    description: "Practica reconociendo ataques reales en un entorno seguro.",
    icon: "🎯",
    difficulty: "intermediate",
    estimatedMinutes: 60,
    prerequisites: ["phishing"],
    lessons: [
      { slug: "lesson-1", title: "Qué son los simuladores de phishing", order: 1 },
      { slug: "lesson-2", title: "Cómo funciona un ataque de robo de credenciales", order: 2 },
      { slug: "lesson-3", title: "Señales de alerta en pantallas falsas", order: 3 },
      { slug: "lesson-4", title: "Practica con el simulador — Google", order: 4 },
      { slug: "lesson-5", title: "Practica con el simulador — Banco", order: 5 },
    ],
  },
  {
    slug: "wifi",
    title: "Seguridad en redes WiFi",
    description: "Aprende los peligros del WiFi público, cómo proteger tu red en casa, y qué hacer cuando viajas.",
    icon: "📶",
    difficulty: "basic",
    estimatedMinutes: 50,
    prerequisites: [],
    lessons: [
      { slug: "lesson-1", title: "Los peligros del WiFi público", order: 1 },
      { slug: "lesson-2", title: "Cómo funciona un ataque man in the middle", order: 2 },
      { slug: "lesson-3", title: "VPN — qué es y cuándo usarla", order: 3 },
      { slug: "lesson-4", title: "Cómo proteger tu red WiFi en casa", order: 4 },
      { slug: "lesson-5", title: "WiFi en hoteles y aeropuertos", order: 5 },
    ],
  },
  {
    slug: "social-media",
    title: "Seguridad en redes sociales",
    description: "Controla qué compartes, detecta perfiles falsos y estafas, y protege a tu familia en el mundo digital.",
    icon: "📱",
    difficulty: "basic",
    estimatedMinutes: 60,
    prerequisites: [],
    lessons: [
      { slug: "lesson-1", title: "Qué información nunca debes publicar", order: 1 },
      { slug: "lesson-2", title: "Configuración de privacidad en Instagram y Facebook", order: 2 },
      { slug: "lesson-3", title: "Cuentas falsas e ingeniería social", order: 3 },
      { slug: "lesson-4", title: "Estafas comunes en redes sociales", order: 4 },
      { slug: "lesson-5", title: "Niños y redes sociales", order: 5 },
      { slug: "lesson-6", title: "Cómo limpiar tu huella digital", order: 6 },
    ],
  },
  {
    slug: "pass-manager",
    title: "Gestores de contraseñas",
    description: "Todo lo que necesitas saber para elegir, configurar y sacarle el máximo partido a un gestor de contraseñas.",
    icon: "🗄️",
    difficulty: "basic",
    estimatedMinutes: 60,
    prerequisites: ["passwords"],
    lessons: [
      { slug: "lesson-1", title: "Por qué un gestor de contraseñas cambia tu vida digital", order: 1 },
      { slug: "lesson-2", title: "Cómo elegir un gestor de contraseñas", order: 2 },
      { slug: "lesson-3", title: "Primeros pasos con tu gestor", order: 3 },
      { slug: "lesson-4", title: "Importar y organizar tus contraseñas", order: 4 },
      { slug: "lesson-5", title: "Usar el gestor en el móvil", order: 5 },
      { slug: "lesson-6", title: "Qué pasa si el gestor es hackeado", order: 6 },
    ],
  },
  {
    slug: "device-security",
    title: "Seguridad en dispositivos",
    description: "Protege tu teléfono y computadora con actualizaciones, cifrado, permisos y un plan si te lo roban.",
    icon: "🛡️",
    difficulty: "basic",
    estimatedMinutes: 50,
    prerequisites: [],
    lessons: [
      { slug: "lesson-1", title: "Actualizaciones de seguridad", order: 1 },
      { slug: "lesson-2", title: "Antivirus — qué hace y cuáles son confiables", order: 2 },
      { slug: "lesson-3", title: "Bloqueo de pantalla y cifrado", order: 3 },
      { slug: "lesson-4", title: "Permisos de aplicaciones", order: 4 },
      { slug: "lesson-5", title: "Qué hacer si te roban el teléfono", order: 5 },
    ],
  },
];
